### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by KyGost** [KyGost/QCT#1]
- [x] Changing gates
- [ ] Better testing
- [x] Better UI
- [x] Better valuation formula
- [x] Qubit decrement
- [ ] Train a model which can be used to generate values for models
- [ ] Even better valuation formula
- [ ] Config struct
- [ ] Cleanup
- [ ] Reasonable Changing Gates
- [x] Inputs can increase with iterations but should not shuffle
- [ ] Cleaner input method

**Comment by KyGost** [comment]
I'm thinking that there are big limits to what I'm going to be able to do with just a circuit.
I'll probably *need* to make it so that there is a learnt model that *makes* circuits.

**Comment by KyGost** [comment]
It's going to be a better idea to, rather than abusing very large numbers of models, work on making it so higher number of iterations give good results.
